#!/usr/bin/perl
use strict;
use warnings;
use 5.010;
use Encode;

# Try
#   uni2utf 01f4a9 01f600 f7 | bash

foreach (@ARGV) {
    my ($s, $x);
    $s = encode('utf8', chr(hex($_)));
    $x = unpack('H*', $s);
    $x =~ s/(..)/\\x$1/g;
    say "echo -e '$x'  # '$s'";
}
