#!/usr/bin/perl
use strict;
use warnings;
use 5.010;
use Encode;

# Try
#   uni2utf 01f4a9 01f600 f7 | bash

foreach (@ARGV) {
    my $s;
    $s = unpack('H*', encode('utf8', chr(hex($_))));
    $s =~ s/(..)/\\x$1/g;
    say "echo -e '$s'";
}
